# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  reset-test-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: neondatabase/reset-branch-action@v1
      with:
        project_id: lucky-resonance-56682361
        parent: true
        branch: test-database
        api_key: ${{ vars.NEON_API_KEY }}
      id: reset-branch
    - run: echo branch_id ${{ steps.reset-branch.outputs.branch_id }}


  test-build-server:
  
    runs-on: ubuntu-latest
    needs: [reset-test-branch]
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: npm ci
    - run: npm test --if-present
    - run: npm run build --if-present


  test-build-client:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: npm ci
    - run: npm test --if-present
    - run: npm run build --if-present